services:
  - type: web
    name: sweet-home-expense-manager
    runtime: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_NAME
        sync: false
      - key: ADMIN_MOBILE
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
